//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountType
    {
        public long id { get; set; }
        public string AccType { get; set; }
        public string AccDescription { get; set; }
        public Nullable<bool> AccIsDeleted { get; set; }
        public Nullable<System.DateTime> AccDateCreated { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
