//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approval
    {
        public long Table_id { get; set; }
        public string TableName { get; set; }
        public Nullable<bool> IsApprovalReqAdd { get; set; }
        public Nullable<bool> IsApprovalReqEdit { get; set; }
        public Nullable<bool> IsApprovalReqDelete { get; set; }
        public Nullable<long> FirstApprover { get; set; }
        public Nullable<long> SecondApprover { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
