//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardTopup
    {
        public long Card_topup_id { get; set; }
        public Nullable<decimal> Card_Amount { get; set; }
        public Nullable<long> Card_Channel { get; set; }
        public string Card_Modeofpayment { get; set; }
        public string Card_Reference { get; set; }
        public Nullable<long> Card_topupby { get; set; }
        public Nullable<System.DateTime> Card_topupdate { get; set; }
        public Nullable<long> Card_id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsAddApproved { get; set; }
        public Nullable<bool> IsDelApproved { get; set; }
        public Nullable<bool> IsEditApproved { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
