//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public long Card_id { get; set; }
        public string Card_UID { get; set; }
        public string Card_SNO { get; set; }
        public Nullable<int> Card_Type { get; set; }
        public Nullable<long> Card_Owner { get; set; }
        public Nullable<long> Card_Owner_Employee { get; set; }
        public Nullable<decimal> Card_Balance { get; set; }
        public Nullable<int> Card_Points_Balance { get; set; }
        public Nullable<decimal> Card_OverDraftValue { get; set; }
        public Nullable<decimal> Card_PrepaidAmt { get; set; }
        public Nullable<bool> Card_IsAssigned { get; set; }
        public Nullable<bool> Card_IsActive { get; set; }
        public Nullable<bool> Card_IsDeleted { get; set; }
        public Nullable<System.DateTime> Card_DateAssigned { get; set; }
        public Nullable<System.DateTime> Card_UploadDate { get; set; }
        public Nullable<System.DateTime> Card_UpdateDate { get; set; }
        public string Card_PIN { get; set; }
        public Nullable<bool> Card_IsAssignedtoEmp { get; set; }
        public Nullable<decimal> Card_CreditLimit { get; set; }
        public Nullable<System.DateTime> Card_CreditLimit_Expiration { get; set; }
        public Nullable<bool> IsAddApproved { get; set; }
        public Nullable<bool> IsEditApproved { get; set; }
        public Nullable<bool> IsDelApproved { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
