//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public long Channel_id { get; set; }
        public string Channel_Name { get; set; }
        public string Channel_Description { get; set; }
        public Nullable<long> Channel_Type { get; set; }
        public string Channel_Country { get; set; }
        public string Channel_Address { get; set; }
        public string Channel_City { get; set; }
        public Nullable<bool> Channel_IsDeleted { get; set; }
        public Nullable<bool> Channel_IsActive { get; set; }
        public Nullable<System.DateTime> Channel_DateCreated { get; set; }
        public Nullable<bool> Channel_IsSelected { get; set; }
        public Nullable<bool> IsAddApproved { get; set; }
        public Nullable<bool> IsDelApproved { get; set; }
        public Nullable<bool> IsEditApproved { get; set; }
        public Nullable<int> IsDeletedFlag { get; set; }
        public Nullable<bool> IsbeingEdited { get; set; }
        public string CF1 { get; set; }
        public string CF2 { get; set; }
        public string CF3 { get; set; }
        public string CF4 { get; set; }
        public string CF5 { get; set; }
        public string CF6 { get; set; }
        public string CF7 { get; set; }
        public string CF8 { get; set; }
        public string CF9 { get; set; }
        public string CF10 { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
