//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_AuditTrail
    {
        public long id { get; set; }
        public Nullable<long> Staff_Id { get; set; }
        public string Field_Name { get; set; }
        public string FieldValueBeforeChange { get; set; }
        public string FieldValueAfterChange { get; set; }
        public Nullable<System.DateTime> DateofChange { get; set; }
        public Nullable<long> Customer_Id { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
