//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Account
    {
        public long AccountNumber { get; set; }
        public Nullable<long> Customer_id { get; set; }
        public Nullable<long> AccountType_id { get; set; }
        public string Mask_Type { get; set; }
        public string Mask { get; set; }
        public Nullable<int> CreditType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public bool IsCollection { get; set; }
        public Nullable<long> Employee_id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
