//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_AccountTopup
    {
        public long AccountTopup_id { get; set; }
        public Nullable<long> AccountNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> Channel_id { get; set; }
        public string Modeofpayment { get; set; }
        public string ERPRef { get; set; }
        public string ChequeNo { get; set; }
        public string BankAccountNo { get; set; }
        public string Reference { get; set; }
        public Nullable<long> Topupby { get; set; }
        public Nullable<System.DateTime> Topupdate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> Finance_Transaction_id { get; set; }
        public string DrawerBankName { get; set; }
        public string PayeeBankName { get; set; }
        public string BranchDeposited { get; set; }
        public string DepositSlipNumber { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
