//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_AccountUsageLimit
    {
        public long UsageLimit_id { get; set; }
        public Nullable<long> UsageLimit_AccountNumber { get; set; }
        public Nullable<long> UsageLimit_Product_id { get; set; }
        public Nullable<decimal> UsageLimit_Value { get; set; }
        public Nullable<System.DateTime> UsageLimit_DateCreated { get; set; }
        public Nullable<long> UsageLimit_Type { get; set; }
        public Nullable<bool> UsageLimit_IsOverall { get; set; }
        public Nullable<bool> UsageLimit_IsActive { get; set; }
        public Nullable<bool> UsageLimit_IsDeleted { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
