//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_PriceList
    {
        public long id { get; set; }
        public Nullable<long> Customer_id { get; set; }
        public Nullable<long> Price_List_id { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
