//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long Customer_id { get; set; }
        public string Customer_FirstName { get; set; }
        public string Customer_MiddleName { get; set; }
        public string Customer_LastName { get; set; }
        public string Customer_OtherName { get; set; }
        public Nullable<System.DateTime> Customer_DoB { get; set; }
        public string Customer_Gender { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_Password { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Country { get; set; }
        public Nullable<long> Customer_Role { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsVerificationMailSent { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> VerificationMailDate { get; set; }
        public Nullable<System.DateTime> PasswordResetLnkDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public Nullable<bool> IsAddApproved { get; set; }
        public Nullable<bool> IsDelApproved { get; set; }
        public Nullable<bool> IsEditApproved { get; set; }
        public Nullable<int> TotalEmp { get; set; }
        public string ReportingPassword { get; set; }
        public Nullable<long> Payment_Term_id { get; set; }
        public Nullable<bool> AutoRedistributeFunds { get; set; }
        public Nullable<long> Price_List_id { get; set; }
        public Nullable<long> Discount_List_id { get; set; }
        public string CustomerDesignation { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> CustomerTaxCategoryID { get; set; }
        public string Customer_PIN { get; set; }
        public string Customer_IDNumber { get; set; }
        public string Customer_PostalAddress { get; set; }
        public string Customer_PostalCode { get; set; }
        public string Customer_Mobile { get; set; }
        public string Customer_ContactNoHome { get; set; }
        public string Customer_ContactNoOffice { get; set; }
        public string Customer_Fax { get; set; }
        public string NOK_FirstName { get; set; }
        public string NOK_MiddleName { get; set; }
        public string NOK_LastName { get; set; }
        public string NOK_Email { get; set; }
        public string NOK_Phone { get; set; }
        public string Customer_BankName { get; set; }
        public string Customer_BankBranch { get; set; }
        public string Customer_AccountNumber { get; set; }
        public string Customer_AccountCurrency { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> CompanyIncorporationDate { get; set; }
        public string CompanyRegistrationNo { get; set; }
        public string CompanyPIN { get; set; }
        public string CompanyVAT { get; set; }
        public string CompanyPostalAddress { get; set; }
        public string CompanyPostalCode { get; set; }
        public string CompanyCountry { get; set; }
        public string CompanyPhysicalAddress { get; set; }
        public string CompanyPhysicalPostalCode { get; set; }
        public string CompanyPhysicalAddressCountry { get; set; }
        public string CompanyDirectorFirstName1 { get; set; }
        public string CompanyDirectorMiddleName1 { get; set; }
        public string CompanyDirectorLastName1 { get; set; }
        public string CompanyDirectorEmail1 { get; set; }
        public string CompanyDirectorPhone1 { get; set; }
        public string CompanyDirectorPIN1 { get; set; }
        public string CompanyDirectorID1 { get; set; }
        public string CompanyDirectorFirstName2 { get; set; }
        public string CompanyDirectorMiddleName2 { get; set; }
        public string CompanyDirectorLastName2 { get; set; }
        public string CompanyDirectorEmail2 { get; set; }
        public string CompanyDirectorPhone2 { get; set; }
        public string CompanyDirectorPIN2 { get; set; }
        public string CompanyDirectorID2 { get; set; }
        public string CompanyDirectorFirstName3 { get; set; }
        public string CompanyDirectorMiddleName3 { get; set; }
        public string CompanyDirectorLastName3 { get; set; }
        public string CompanyDirectorEmail3 { get; set; }
        public string CompanyDirectorPhone3 { get; set; }
        public string CompanyDirectorPIN3 { get; set; }
        public string CompanyDirectorID3 { get; set; }
        public string CompanyContactPersonName1 { get; set; }
        public string CompanyContactPersonPosition1 { get; set; }
        public string CompanyContactPersonEmail1 { get; set; }
        public string CompanyContactPersonPhone1 { get; set; }
        public string CompanyContactPersonName2 { get; set; }
        public string CompanyContactPersonPosition2 { get; set; }
        public string CompanyContactPersonEmail2 { get; set; }
        public string CompanyContactPersonPhone2 { get; set; }
        public string CF1 { get; set; }
        public string CF2 { get; set; }
        public string CF3 { get; set; }
        public string CF4 { get; set; }
        public string CF5 { get; set; }
        public string CF6 { get; set; }
        public string CF7 { get; set; }
        public string CF8 { get; set; }
        public string CF9 { get; set; }
        public string CF10 { get; set; }
    }
}
