//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long Emp_id { get; set; }
        public Nullable<long> Emp_Customer_id { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Description { get; set; }
        public string Emp_Email { get; set; }
        public string Emp_Phone { get; set; }
        public Nullable<bool> Emp_IsActive { get; set; }
        public Nullable<bool> Emp_IsDeleted { get; set; }
        public Nullable<System.DateTime> Emp_DateCreated { get; set; }
        public Nullable<bool> IsAddApproved { get; set; }
        public Nullable<bool> IsDelApproved { get; set; }
        public Nullable<bool> IsEditApproved { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
