//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FuelCardDBEntities : DbContext //This is a data context that allows you to query and work with entity data
    {
        public FuelCardDBEntities()
            : base("name=FuelCardDBEntities") //This is the name of the connection string which will be added to the Web.config later
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //modelBuilder.Entity<Staff>().ToTable("Staff");
            //throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Activity> Activities { get; set; }
        public DbSet<CardTopup> CardTopups { get; set; }
        public DbSet<CardUsageLimit> CardUsageLimits { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Currency> Currencies { get; set; }
        public DbSet<CustomerType> CustomerTypes { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Gadget> Gadgets { get; set; }
        public DbSet<Lnk_Customers_CustomerTypes> Lnk_Customers_CustomerTypes { get; set; }
        public DbSet<Lnk_Gadgets_Channels> Lnk_Gadgets_Channels { get; set; }
        public DbSet<Lnk_Products_Channels> Lnk_Products_Channels { get; set; }
        public DbSet<Lnk_Role_Permission> Lnk_Role_Permission { get; set; }
        public DbSet<Loyalty_Scheme> Loyalty_Scheme { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<ProductProperty> ProductProperties { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Tierlevel> Tierlevels { get; set; }
        public DbSet<Tierrule> Tierrules { get; set; }
        public DbSet<Tiertable> Tiertables { get; set; }
        public DbSet<TimeDuration> TimeDurations { get; set; }
        public DbSet<Lnk_Products_Channels_Properties> Lnk_Products_Channels_Properties { get; set; }
        public DbSet<Lnk_Products_Properties> Lnk_Products_Properties { get; set; }
        public DbSet<VwProduct_ProductProperty> VwProduct_ProductProperty { get; set; }
        public DbSet<VwProducts_ProductTypes> VwProducts_ProductTypes { get; set; }
        public DbSet<VwChannels_ChannelTypes> VwChannels_ChannelTypes { get; set; }
        public DbSet<VwChannelProducts> VwChannelProducts { get; set; }
        public DbSet<VwChannelGadgets> VwChannelGadgets { get; set; }
        public DbSet<Customer_Roles> Customer_Roles { get; set; }
        public DbSet<CustomerPermissions> CustomerPermissions { get; set; }
        public DbSet<LnkCustomer_Role_Permission> LnkCustomer_Role_Permission { get; set; }
        public DbSet<Cards> Cards { get; set; }
        public DbSet<VwCardsCustomers> VwCardsCustomers { get; set; }
        public DbSet<PaymentMode> PaymentMode { get; set; }
        public DbSet<VwCardUsageLimit_Products> VwCardUsageLimit_Products { get; set; }
        public DbSet<ActivityType> ActivityType { get; set; }
        public DbSet<VwActivity_ActivityType> VwActivity_ActivityType { get; set; }
        public DbSet<EventsTbl> EventsTbl { get; set; }
        public DbSet<Loyalty_Program> Loyalty_Program { get; set; }
        public DbSet<CommunicationTemplates> CommunicationTemplates { get; set; }
        public DbSet<Approval> Approval { get; set; }
        public DbSet<Customer_Vehicle> Customer_Vehicle { get; set; }
        public DbSet<Vehicle> Vehicle { get; set; }
        public DbSet<VehicleModel> VehicleModel { get; set; }
        public DbSet<VwVehicle_VehicleModel> VwVehicle_VehicleModel { get; set; }
        public DbSet<WeekDays> WeekDays { get; set; }
        public DbSet<actionitem> actionitems { get; set; }
        public DbSet<conflicting_action> conflicting_action { get; set; }
        public DbSet<refvaluehistory> refvaluehistories { get; set; }
        public DbSet<supplementary_action> supplementary_action { get; set; }
        public DbSet<ActionsTbl> ActionsTbl { get; set; }
        public DbSet<AccountType> AccountType { get; set; }
        public DbSet<AccountType_Action> AccountType_Action { get; set; }
        public DbSet<Customer_Account> Customer_Account { get; set; }
        public DbSet<Customer_AccountTopup> Customer_AccountTopup { get; set; }
        public DbSet<Customer_AccountUsageLimit> Customer_AccountUsageLimit { get; set; }
        public DbSet<Lnk_CustomerVehicle_Account> Lnk_CustomerVehicle_Account { get; set; }
        public DbSet<MaskType> MaskType { get; set; }
        public DbSet<PostpaidAccountCreditLimit> PostpaidAccountCreditLimit { get; set; }
        public DbSet<VwAccUsageLimit_Products> VwAccUsageLimit_Products { get; set; }
        public DbSet<VwTest> VwTest { get; set; }
        public DbSet<PostpaidCustCreditLimits> PostpaidCustCreditLimits { get; set; }
        public DbSet<FormulaValueType> FormulaValueType { get; set; }
        public DbSet<Schedule> Schedule { get; set; }
        public DbSet<VwChannelProductSchedule> VwChannelProductSchedule { get; set; }
        public DbSet<Schedule_History> Schedule_History { get; set; }
        public DbSet<ChartofAccountsSubTypes> ChartofAccountsSubTypes { get; set; }
        public DbSet<ChartofAccounts> ChartofAccounts { get; set; }
        public DbSet<ChartofAccountTypes> ChartofAccountTypes { get; set; }
        public DbSet<GLTransactions> GLTransactions { get; set; }
        public DbSet<Periods> Periods { get; set; }
        public DbSet<AccoutingDocTypes> AccoutingDocTypes { get; set; }
        public DbSet<Finance_Transaction> Finance_Transaction { get; set; }
        public DbSet<Lnk_PriceList_Product> Lnk_PriceList_Product { get; set; }
        public DbSet<Payment_Terms> Payment_Terms { get; set; }
        public DbSet<PriceList> PriceList { get; set; }
        public DbSet<VwPriceListProducts> VwPriceListProducts { get; set; }
        public DbSet<Customer_PriceList> Customer_PriceList { get; set; }
        public DbSet<MessageTypes> MessageTypes { get; set; }
        public DbSet<CustomTableFields> CustomTableFields { get; set; }
        public DbSet<DiscountsList> DiscountsList { get; set; }
        public DbSet<Lnk_Discount_Product> Lnk_Discount_Product { get; set; }
        public DbSet<VwDiscountProducts> VwDiscountProducts { get; set; }
        public DbSet<Customer_AuditTrail> Customer_AuditTrail { get; set; }
        public DbSet<Audit> Audit { get; set; }
        public DbSet<Customer_TaxCategory> Customer_TaxCategory { get; set; }
        public DbSet<Tax> Tax { get; set; }
        public DbSet<TaxCategory> TaxCategory { get; set; }
        public DbSet<TaxRate> TaxRate { get; set; }
        public DbSet<VwTax> VwTax { get; set; }
        public DbSet<VwCustomerAccount> VwCustomerAccount { get; set; }
        public DbSet<VwCustomerEmpAccount> VwCustomerEmpAccount { get; set; }
        public DbSet<GeneralSetting> GeneralSettings { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<ChannelType> ChannelTypes { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<VwCreditLimit> VwCreditLimit { get; set; }
        public DbSet<ReceiptSettings> ReceiptSettings { get; set; }
        public DbSet<Channel> Channels { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<VwCustomers> VwCustomers { get; set; }
    }
}
