//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLTransactions
    {
        public long GlTrans_id { get; set; }
        public Nullable<long> Finance_Transaction_id { get; set; }
        public Nullable<long> Amount { get; set; }
        public string Currency { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> GlTrans_DateCreated { get; set; }
        public Nullable<long> ChartofAccount_id { get; set; }
        public Nullable<long> Period_id { get; set; }
        public Nullable<System.DateTime> GLTrans_Actual_DateCreated { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
