//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lnk_Products_Channels_Properties
    {
        public long Lnk_Products_Ch_Properties_id { get; set; }
        public Nullable<long> Product_id { get; set; }
        public Nullable<long> Channel_id { get; set; }
        public Nullable<long> Product_Property_id { get; set; }
        public string Product_Property_Value { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
