//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lnk_Customers_CustomerTypes
    {
        public long Lnk_Cust_CustType_id { get; set; }
        public Nullable<long> Customer_id { get; set; }
        public Nullable<long> CustomerType_id { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
