//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lnk_Discount_Product
    {
        public long id { get; set; }
        public Nullable<long> Product_id { get; set; }
        public Nullable<long> Channel_id { get; set; }
        public Nullable<long> Discount_List_id { get; set; }
        public Nullable<decimal> Discount_Value { get; set; }
        public string Discount_Currency { get; set; }
        public string Discount_Type { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
