//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lnk_Gadgets_Channels
    {
        public long Lnk_Gadgets_Channels_id { get; set; }
        public Nullable<long> Gadget_id { get; set; }
        public Nullable<long> Channel_id { get; set; }
        public Nullable<bool> Lnk_Gadget_IsActive { get; set; }
        public Nullable<bool> Lnk_Gadget_IsDeleted { get; set; }
        public Nullable<System.DateTime> Lnk_Gadget_DateCreated { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
