//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lnk_Products_Channels
    {
        public long Lnk_Products_Channels_id { get; set; }
        public Nullable<long> Product_id { get; set; }
        public Nullable<long> Channel_id { get; set; }
        public Nullable<decimal> Product_Price { get; set; }
        public string Product_currency { get; set; }
        public Nullable<bool> Product_IsActive { get; set; }
        public Nullable<bool> Product_IsDeleted { get; set; }
        public Nullable<System.DateTime> Product_DateCreated { get; set; }
        public Nullable<long> PriceSchedule_Id { get; set; }
        public Nullable<decimal> Scheduled_Price { get; set; }
        public Nullable<long> Price_List_id { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
