//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loyalty_Program
    {
        public long id { get; set; }
        public string Loyalty_Program_Name { get; set; }
        public Nullable<long> time_period { get; set; }
        public Nullable<long> period_type { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<long> day { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public Nullable<long> action_id { get; set; }
        public Nullable<long> commprotocol_id { get; set; }
        public Nullable<long> tierlevel_id { get; set; }
        public Nullable<long> tierrule_id { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsExclusive { get; set; }
        public Nullable<bool> IsDiscontinued { get; set; }
        public Nullable<bool> IsAddApproved { get; set; }
        public Nullable<bool> IsDelApproved { get; set; }
        public Nullable<bool> IsEditApproved { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
