//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loyalty_Scheme
    {
        public long id { get; set; }
        public string Loyalty_Scheme_Name { get; set; }
        public Nullable<long> loyaltyprogram_id { get; set; }
        public Nullable<long> commprotocol_id { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsExclusive { get; set; }
        public Nullable<bool> IsDiscontinued { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
