//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaskType
    {
        public long id { get; set; }
        public string Mask_Type { get; set; }
        public Nullable<bool> Mask_IsDeleted { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
