//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long id { get; set; }
        public Nullable<long> from_id { get; set; }
        public string customer_type { get; set; }
        public string message_subject { get; set; }
        public string message_body { get; set; }
        public Nullable<System.DateTime> message_date { get; set; }
        public Nullable<long> message_type { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
