//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periods
    {
        public long Period_id { get; set; }
        public Nullable<System.DateTime> LastDate_In_Period { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
