//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceList
    {
        public long PriceList_id { get; set; }
        public string PriceList_Name { get; set; }
        public string PriceList_Description { get; set; }
        public Nullable<bool> PriceList_IsActive { get; set; }
        public Nullable<bool> PriceList_IsDeleted { get; set; }
        public Nullable<System.DateTime> PriceList_DateCreated { get; set; }
        public bool PriceList_IsDefault { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
