//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public long ProductType_id { get; set; }
        public string ProductType_Name { get; set; }
        public string ProductType_Description { get; set; }
        public Nullable<bool> ProductType_IsActive { get; set; }
        public Nullable<bool> ProductType_IsDeleted { get; set; }
        public Nullable<System.DateTime> ProductType_DateCreated { get; set; }
        public Nullable<bool> IsAddApproved { get; set; }
        public Nullable<bool> IsDelApproved { get; set; }
        public Nullable<bool> IsEditApproved { get; set; }
        public Nullable<int> ProductType_IsDeletedFlag { get; set; }
        public Nullable<bool> ProductType_IsbeingDeleted { get; set; }
        public Nullable<bool> ProductType_IsbeingEdited { get; set; }
        public Nullable<bool> ProductType_IsbeingAdded { get; set; }
        public Nullable<bool> IsAddApprovedFirstApvr { get; set; }
        public Nullable<bool> IsAddApprovedSecondApvr { get; set; }
        public Nullable<bool> IsDelApprovedFirstApvr { get; set; }
        public Nullable<bool> IsDelApprovedSecondApvr { get; set; }
        public Nullable<bool> IsEditApprovedFirstApvr { get; set; }
        public Nullable<bool> IsEditApprovedSecondApvr { get; set; }
        public string ReasonEditFirstApvr { get; set; }
        public string ReasonEditSecondApvr { get; set; }
        public string ReasonDelFirstApvr { get; set; }
        public string ReasonDelSecondApvr { get; set; }
        public string ReasonAddFirstApvr { get; set; }
        public string ReasonAddSecondApvr { get; set; }
        public string CF1 { get; set; }
        public string CF2 { get; set; }
        public string CF3 { get; set; }
        public string CF4 { get; set; }
        public string CF5 { get; set; }
        public string CF6 { get; set; }
        public string CF7 { get; set; }
        public string CF8 { get; set; }
        public string CF9 { get; set; }
        public string CF10 { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
