//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public long Schedule_Id { get; set; }
        public string Schedule_Name { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
        public Nullable<bool> Schedule_IsActive { get; set; }
        public Nullable<bool> Schedule_IsDeleted { get; set; }
        public Nullable<System.DateTime> Schedule_DateCreated { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
