//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public long Staff_id { get; set; }
        public string Staff_Name { get; set; }
        public string Staff_Email { get; set; }
        public string Staff_Password { get; set; }
        public string Staff_PIN { get; set; }
        public string Staff_Phone { get; set; }
        public Nullable<long> Staff_TopupLimitType { get; set; }
        public Nullable<decimal> Staff_TopupLimitValue { get; set; }
        public Nullable<long> Staff_Channel_id { get; set; }
        public Nullable<long> Staff_Role { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> PasswordResetExpDate { get; set; }
        public Nullable<bool> IsAddApproved { get; set; }
        public Nullable<bool> IsEditApproved { get; set; }
        public Nullable<bool> IsDelApproved { get; set; }
        public string CF1 { get; set; }
        public string CF2 { get; set; }
        public string CF3 { get; set; }
        public string CF4 { get; set; }
        public string CF5 { get; set; }
        public string CF6 { get; set; }
        public string CF7 { get; set; }
        public string CF8 { get; set; }
        public string CF9 { get; set; }
        public string CF10 { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
