//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tierlevel
    {
        public long id { get; set; }
        public string tierlevel_name { get; set; }
        public string tierlevel_description { get; set; }
        public Nullable<long> producttype_id { get; set; }
        public Nullable<long> activity_id { get; set; }
        public Nullable<long> event_id { get; set; }
        public Nullable<long> channel_id { get; set; }
        public Nullable<long> activitytype_id { get; set; }
        public Nullable<long> channeltype_id { get; set; }
        public Nullable<long> country_id { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<bool> tierlevel_IsActive { get; set; }
        public Nullable<bool> tierlevel_IsDelete { get; set; }
        public Nullable<bool> all_items { get; set; }
        public Nullable<bool> all_channels { get; set; }
        public Nullable<bool> all_activities { get; set; }
        public Nullable<long> accounttype_id { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
