//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tierrule
    {
        public long id { get; set; }
        public string tierrule_name { get; set; }
        public string formula { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<bool> tierrule_IsActive { get; set; }
        public Nullable<bool> tierrule_IsDeleted { get; set; }
        public Nullable<bool> IsAddApproved { get; set; }
        public Nullable<bool> IsDelApproved { get; set; }
        public Nullable<bool> IsEditApproved { get; set; }
        public Nullable<long> ValueId { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    }
}
