//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwAccUsageLimit_Products
    {
        public Nullable<long> UsageLimit_Product_id { get; set; }
        public long TimeDuration_id { get; set; }
        public long UsageLimit_id { get; set; }
        public Nullable<long> UsageLimit_AccountNumber { get; set; }
        public Nullable<decimal> UsageLimit_Value { get; set; }
        public Nullable<System.DateTime> UsageLimit_DateCreated { get; set; }
        public Nullable<long> UsageLimit_Type { get; set; }
        public Nullable<bool> UsageLimit_IsOverall { get; set; }
        public Nullable<bool> UsageLimit_IsActive { get; set; }
        public Nullable<bool> UsageLimit_IsDeleted { get; set; }
        public Nullable<long> Product_id { get; set; }
        public string Product_Name { get; set; }
        public string Product_Description { get; set; }
        public Nullable<long> Product_Type { get; set; }
        public Nullable<decimal> Product_Price { get; set; }
        public string Product_currency { get; set; }
        public Nullable<bool> Product_IsActive { get; set; }
        public Nullable<bool> Product_IsDeleted { get; set; }
        public Nullable<System.DateTime> Product_DateCreated { get; set; }
        public string Value { get; set; }
        public string Type { get; set; }
    }
}
