//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwCardsCustomers
    {
        public Nullable<long> Customer_id { get; set; }
        public string Customer_OtherName { get; set; }
        public Nullable<System.DateTime> Customer_DoB { get; set; }
        public string Customer_Gender { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_Password { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Country { get; set; }
        public Nullable<long> Customer_Role { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsVerificationMailSent { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> VerificationMailDate { get; set; }
        public Nullable<System.DateTime> PasswordResetLnkDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public long Card_id { get; set; }
        public string Card_UID { get; set; }
        public string Card_SNO { get; set; }
        public Nullable<int> Card_Type { get; set; }
        public Nullable<long> Card_Owner { get; set; }
        public Nullable<long> Card_Owner_Employee { get; set; }
        public Nullable<decimal> Card_Balance { get; set; }
        public Nullable<int> Card_Points_Balance { get; set; }
        public Nullable<decimal> Card_OverDraftValue { get; set; }
        public Nullable<decimal> Card_PrepaidAmt { get; set; }
        public Nullable<bool> Card_IsAssigned { get; set; }
        public Nullable<bool> Card_IsActive { get; set; }
        public Nullable<bool> Card_IsDeleted { get; set; }
        public Nullable<System.DateTime> Card_DateAssigned { get; set; }
        public Nullable<System.DateTime> Card_UploadDate { get; set; }
        public Nullable<System.DateTime> Card_UpdateDate { get; set; }
        public string Card_PIN { get; set; }
        public Nullable<bool> Card_IsAssignedtoEmp { get; set; }
        public string Customer_FirstName { get; set; }
    }
}
