//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwCardUsageLimit_Products
    {
        public string Product_Name { get; set; }
        public long Card_UsageLimit_id { get; set; }
        public Nullable<long> Card_UsageLimit_Card_id { get; set; }
        public Nullable<long> Card_UsageLimit_Product_id { get; set; }
        public Nullable<decimal> Card_UsageLimit_Value { get; set; }
        public Nullable<System.DateTime> Card_UsageLimit_DateCreated { get; set; }
        public Nullable<long> Card_UsageLimit_Type { get; set; }
        public Nullable<bool> Card_UsageLimit_IsOverall { get; set; }
        public Nullable<bool> Card_UsageLimit_IsActive { get; set; }
        public Nullable<bool> Card_UsageLimit_IsDeleted { get; set; }
        public string Value { get; set; }
        public long TimeDuration_id { get; set; }
    }
}
