//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwChannels_ChannelTypes
    {
        public long ChannelType_id { get; set; }
        public string ChannelType_Name { get; set; }
        public string ChannelType_Description { get; set; }
        public Nullable<bool> ChannelType_IsActive { get; set; }
        public Nullable<bool> ChannelType_IsDeleted { get; set; }
        public Nullable<System.DateTime> ChannelType_DateCreated { get; set; }
        public long Channel_id { get; set; }
        public string Channel_Name { get; set; }
        public string Channel_Description { get; set; }
        public Nullable<long> Channel_Type { get; set; }
        public string Channel_Country { get; set; }
        public string Channel_Address { get; set; }
        public string Channel_City { get; set; }
        public Nullable<bool> Channel_IsDeleted { get; set; }
        public Nullable<bool> Channel_IsActive { get; set; }
        public Nullable<System.DateTime> Channel_DateCreated { get; set; }
        public Nullable<bool> Channel_IsSelected { get; set; }
        public Nullable<bool> IsAddApproved { get; set; }
        public Nullable<bool> IsDelApproved { get; set; }
        public Nullable<bool> IsEditApproved { get; set; }
        public Nullable<int> IsDeletedFlag { get; set; }
    }
}
