//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwCreditLimit
    {
        public string Customer_Name { get; set; }
        public Nullable<long> Credit_id { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<System.DateTime> CreditLimit_Expiration { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreditType { get; set; }
        public Nullable<long> Customer_id { get; set; }
        public Nullable<long> Cust_id { get; set; }
        public long Expr1 { get; set; }
        public long AccountNumber { get; set; }
        public string CustomerDesignation { get; set; }
        public string CompanyName { get; set; }
    }
}
