//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwCustomerEmpAccount
    {
        public string Customer_FirstName { get; set; }
        public string Customer_MiddleName { get; set; }
        public string Customer_LastName { get; set; }
        public Nullable<long> Emp_id { get; set; }
        public string Emp_Name { get; set; }
        public long AccountNumber { get; set; }
        public Nullable<long> Customer_id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
