//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelCardSystemEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwProduct_ProductProperty
    {
        public long ProductProperty_id { get; set; }
        public string ProductProperty_Name { get; set; }
        public string ProductProperty_Description { get; set; }
        public Nullable<System.DateTime> ProductProperty_DateCreated { get; set; }
        public Nullable<bool> ProductProperty_IsActive { get; set; }
        public Nullable<bool> ProductProperty_IsDeleted { get; set; }
        public long Lnk_Products_Properties_id { get; set; }
        public Nullable<long> Product_id { get; set; }
        public Nullable<long> Product_Property_id { get; set; }
        public Nullable<System.DateTime> Product_Property_DateCreated { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsAddApproved { get; set; }
        public Nullable<bool> IsDelApproved { get; set; }
        public Nullable<bool> IsEditApproved { get; set; }
        public Nullable<int> IsDeletedFlag { get; set; }
        public Nullable<bool> IsbeingDeleted { get; set; }
        public Nullable<bool> IsbeingEdited { get; set; }
        public Nullable<bool> IsbeingAdded { get; set; }
    }
}
